### ISSUE TITLE
There is a programable error in Sphinx configuration

### ISSUE THREAD

**Issue by glenjarvis** [glenjarvis/github_commit_status#2]
## Bug Report

Details:

* Commit: Output of github_commit_status --version`: Version 0.0.1
* Python version: Output of `python --version`: Python 3.6.5
* Operating System: OSX

### What did you expect?

When building the Sphinx documentation, we see the following error:
```
Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/github-commit-status/envs/stable/local/lib/python2.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/github-commit-status/envs/stable/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/github-commit-status/envs/stable/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 59, in <module>
    version = github_commit_status.__version__
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by glenjarvis** [comment]
This has been fixed by PR: https://github.com/glenjarvis/github_commit_status/pull/3
